### ISSUE TITLE
logger.go -> panic: runtime error: index out of range

### ISSUE THREAD

**Issue by PumpkinSeed** [snwfdhmp/errlog#5]
I wanted to try the `examples/basic` and run into the following panic. 
MacOS 10.14.2
go version go1.12 darwin/amd64

```
go run main.go 
Start of the program
I do things !
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/snwfdhmp/errlog.(*logger).Debug(0x151eec0, 0x13445e0, 0xc000116000, 0xc000116000)
	/Users/loow/gopath/src/github.com/snwfdhmp/errlog/logger.go:83 +0x31a
github.com/snwfdhmp/errlog.Debug(0x13445e0, 0xc000116000, 0xc0000c9f08)
	/Users/loow/gopath/src/github.com/snwfdhmp/errlog/errlog.go:89 +0x4d
main.someBigFunction()
```

**Comment by snwfdhmp** [comment]
Diving into it :) Thanks for your feedback

**Comment by snwfdhmp** [comment]
I can't reproduce, can you give more details ?

![image](https://user-images.githubusercontent.com/23099246/53746397-5f3cfd00-3ea1-11e9-93ec-41f0e23d63d9.png)

This is what I have currently.

I found how the error occured, so I handle it now, but cannot reproduce so cannot test and fix.

The error came from unexpected empty stack trace.
I added a few lines to handle this error properly.

```golang
if len(stLines) < 1 {
		l.Printf("Error: %s", uErr)
		l.Printf("Errlog tried to debug the error but the stack trace seems empty. If you think this is an error, please open an issue at https://github.com/snwfdhmp/errlog/issues/new and provide us logs to investigate.")
		return true
	}
```

**Comment by PumpkinSeed** [comment]
I found out that the `parsedRes := regexpParseStack.FindAllStringSubmatch(stack, -1)` returns an empty array, however the `stack` has the following string inside:
```
	/Users/loow/gopath/src/github.com/snwfdhmp/errlog/errlog.go:89 +0x4d
main.someBigFunction()
	/Users/loow/gopath/src/github.com/PumpkinSeed/adventure-of-golang/errlog/main.go:29 +0xc8
main.wrapingFunc(...)
	/Users/loow/gopath/src/github.com/PumpkinSeed/adventure-of-golang/errlog/main.go:19
main.main()
	/Users/loow/gopath/src/github.com/PumpkinSeed/adventure-of-golang/errlog/main.go:13 +0x80
```
So somehow the regexp won't find any match. You can find it in the regexp.go line 42

**Comment by snwfdhmp** [comment]
@PumpkinSeed It's fixed now.

Thank you for your precious feedback. That is really appreciated !
