### ISSUE TITLE
[Feature] Allow runtime enabling/disabling of output

### ISSUE THREAD

**Issue by Kirides** [snwfdhmp/errlog#7]
Started through: https://www.reddit.com/r/golang/comments/bzbwrz/hackable_error_handling_package_using_stacktrace/equsunu

Allow to enable/disable the logger output using something like
```
errlog.SetActive(bool)
// or errlog.SetLogOutput(bool)
// or errlog.SetOutput(io.Writer / nil)
```

**Comment by snwfdhmp** [comment]
Hi @Kirides, Thanks for your proposal.

**I've added this feature today into errlog's master branch.**

More information :

1. The `Logger` type comes now with the `Disable(bool)` func. After disabling it, the Logger will perform NO-OP for each call to Debug(). (thus inducing no performance cost when disabled)
2. There is already a `Config` parameter for changing the output writer. Its name is `PrintFunc` of type `func(format string, data ...interface{})`.
